### ISSUE TITLE
The output is '' when generate  on coco dataset

### ISSUE THREAD

**Issue by shipengai** [opendatalab/VIGC#12]
when run "evaluate.py --cfg-path vigc/projects/mini_gpt4_vicuna7b/generate_qa/llava-150k/generate_llava_qa_conv.yaml"

vigc/tasks/llava_150k_gen.py
line 217
The value of answers is ['', '', '', '', '', '', '', '']

this_sample['image'].shape is 8* 3 * 224*224
this_sample['prompt'] is ['Generate a question ...answer it.', 'Generate a question ...answer it.', 'Generate a question ...answer it.', 'Generate a question ...answer it.', 'Generate a question ...answer it.', 'Generate a question ...answer it.', 'Generate a question ...answer it.', 'Generate a question ...answer it.']

**Comment by HanxSmile** [comment]
Hello, have you prepared the `pretrain` weight, `finetune` weight and `llm_model` correctly in `vigc/configs/models/mini_gpt4_vicuna7b.yaml`?
```yaml
model:
  arch: instruct_vicuna7b
  load_finetuned: True
  load_pretrained: True

  pretrained: "path/to/pretrained/weight"
  finetuned: "path/to/finetuned/weight"

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # path to Vicuna checkpoint
  llm_model: "path/to/vicuna/weight"

```

**Comment by shipengai** [comment]
@HanxSmile,yes, this is my config file

```
model:
  arch: instruct_vicuna7b
  load_finetuned: True
  load_pretrained: True

  pretrained: "pretained_weights/minigpt4//pretrained_minigpt4_7b_stage1.pth"
  finetuned: "pretained_weights/vigc7b_minigpt4_llava/vigc7b_minigpt4_llava.pth"

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # path to Vicuna checkpoint
  llm_model: "pretained_weights/vicuna-7b"

  # generation configs
  prompt: ""
```
