### ISSUE TITLE
The difference between paper and code when generate detailed description

### ISSUE THREAD

**Issue by shipengai** [opendatalab/VIGC#14]
In the paper, the section of "Visual Instruction Correction" says "......this process continues iteratively until a termination symbol is encountered"
But, in the code, there is a "answer_length" variable .it is a constant num e.g. 4 in the config file.
[https://github.com/opendatalab/VIGC/blob/main/vigc/tasks/llava_150k_gen.py#L215](url)
So, it is different with paper. it only have 1+4 iterations. The answer is uncompleted
this is the "vigc/projects/mini_gpt4_vicuna13b/generate_qa/llava-150k/generate_llava_qa_detail.yaml"
```
datasets:
  instruct_blip_coco2017_vig_test: # name of the dataset builder

    filter:
      - llava
    vis_processor:
      eval:
        name: "blip_image_eval"
        image_size: 224
    text_processor:
      eval:
        name: "blip_caption_instruct"
        max_words: 256

run:
  runner: runner_iter
  task: instruct_blip_llava_vig
  answer_length: 4
  llava_task: desc  # desc, comp or conv
  gen_style: vig  # vig or vic

  batch_size_train: 16
  batch_size_eval: 8
  num_workers: 4

  iters_per_inner_epoch: 2000
  max_iters: 60000

  seed: 42
  output_dir: "output/result/minigpt4_13b_llava/detail"

  evaluate: True
  test_splits: [ "eval" ]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  generate_cfg:
    max_len: 250
    min_len: 1
    num_beams: 5
```

**Comment by shipengai** [comment]
So, when use the llava-150k/generate_llava_qa_detail.yaml, it can not generate the same result with VIGC-InstData. Can you share the same config file with VIGC-InstData?

**Comment by wufan-tb** [comment]
Hi @shipengai , there is a config key named "last_infer_all"(means keep all sentence at last iteration), you can set it to `True` like this: 
```
run:
  runner: runner_iter
  task: instruct_blip_llava_vig
  answer_length: 4
  last_infer_all: True
  ...
```
through this way, you can get a completed answer.  
  
by the way, the value of  "last_infer_all" is `False` by default, you can visit the source code for more details: https://github.com/opendatalab/VIGC/blob/a1aa9f12804a816c285b600c22d4ef8c299199ae/vigc/tasks/llava_150k_gen.py#L105

**Comment by shipengai** [comment]
@wufan-tb Thanks for your reply.But it is still different with the paper that says ".....this process continues iteratively until a termination symbol is encountered""
Is the  VIGC-InstData also use "last_infer_all =True" ?
Another question is about the key named "in_section", how to set it if i want generate the same data with  VIGC-InstData [https://opendatalab.com/OpenDataLab/VIGC-InstData](url)

**Comment by wufan-tb** [comment]
when generated the released VIGC-InstData, we set `last_infer_all = True`, and `in_section = False`

**Comment by shipengai** [comment]
@wufan-tb. The result is still different with VIGC-InstData.
for example, {'image_id': 473109, 'image': 'train2017/000000473109.jpg'}
The answer of VIGC-InstData is 
`The image features a man wearing a blue shirt and a bow tie, looking at the camera with a serious expression. The man has a bald head, and he appears to be in an office setting, as evidenced by the presence of a desk in the background. The man's attire, consisting of a blue shirt and a bow tie, suggests that he may be attending a formal event or working in a professional environment. Overall, the image conveys a sense of professionalism and attention to detail in the man's appearance.`
The answer of my result is 
`The image features a close-up shot of a man wearing a shirt and tie. The man's face is prominently displayed in the center of the image, with the shirt and tie taking up most of the frame. The shirt appears to be blue, and the tie has a polka-dot pattern. The man's facial expression is neutral, and he appears to be looking directly at the camera. The overall composition of the image emphasizes the man's attire, with the shirt and tie taking center stage and the man's face providing a focal point for the viewer's attention.`

my config is vigc/projects/mini_gpt4_vicuna7b/generate_qa/llava-150k/generate_llava_qa_detail.yaml
```
model:
  arch: blip2_vicuna_instruct
  model_type: minigpt4_vicuna7b
  finetuned: "pretained_weights/vigc7b_minigpt4_llava/vigc7b_minigpt4_llava.pth"

datasets:
  instruct_blip_coco2017_vig_test: # name of the dataset builder

    filter:
      - llava
    vis_processor:
      eval:
        name: "blip_image_eval"
        image_size: 224
    text_processor:
      eval:
        name: "blip_caption_instruct"
        max_words: 256

run:
  runner: runner_iter
  task: instruct_blip_llava_vig
  answer_length: 4
  last_infer_all: True
  llava_task: desc  # desc, comp or conv
  gen_style: vig  # vig or vic

  batch_size_train: 16
  batch_size_eval: 1
  num_workers: 4

  iters_per_inner_epoch: 2000
  max_iters: 60000

  seed: 42
  output_dir: "output/result/minigpt4_7b_llava/detail"

  evaluate: True
  test_splits: [ "eval" ]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  generate_cfg:
    max_len: 250
    min_len: 1
    num_beams: 5
```
the config of vigc/configs/models/mini_gpt4_vicuna7b.yaml is 
```
model:
  arch: instruct_vicuna7b
  load_finetuned: True
  load_pretrained: True

  pretrained: "pretained_weights/minigpt4//pretrained_minigpt4_7b_stage1.pth"
  finetuned: "pretained_weights/vigc7b_minigpt4_llava/vigc7b_minigpt4_llava.pth"

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # path to Vicuna checkpoint
  llm_model: "pretained_weights/vicuna-7b-v1.1"

  # generation configs
  prompt: ""


preprocess:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
        eval:
          name: "blip_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
```

**Comment by shipengai** [comment]
@wufan-tb by the way, I test with demo [https://opendatalab.github.io/VIGC/](url) , the result of minigpt4 is 
```
Question: Can you describe the main features of this image for me? 

Answer: The image features a man wearing a blue shirt and a bow tie, looking at the camera with a serious expression. He has a bald head, which adds a unique touch to his overall appearance. The man's choice of attire, including the bow tie, suggests that he might be attending a formal or semi-formal event, such as a wedding, a business meeting, or a social gathering. The man's facial expression and the way he is looking at the camera convey a sense of confidence and professionalism. The bow tie adds a touch of elegance and sophistication to his appearance, making him stand out from the crowd. The man's bald head, on the other hand, might be perceived as unique or distinctive, depending on the context of the event and the individual's personal style. 

Overall, the image showcases a well-dressed man with a serious expression, who is likely attending a formal or semi-formal event. The man's choice of attire, including the bow tie, adds a touch of elegance and sophistication to his appearance, while his bald head might be perceived as unique or distinctive, depending on the context of the event and the individual's personal style.
```

**Comment by wufan-tb** [comment]
it is normal that laguage model generate tokens with some randomness, it should has no impact on downstream tasks. 

here is our generation config, you can take it as a reference:

```
  answer_length: 4
  last_infer_all: True
  llava_task: desc  # desc, comp or conv
  gen_style: vqga  # vqga or vqa

  batch_size_train: 16
  batch_size_eval: 8
  num_workers: 4

  iters_per_inner_epoch: 2000
  max_iters: 60000

  seed: 42
  output_dir: output/results/vigc7b/minigpt4_vigc7b_stage2_gen_detail

  evaluate: True
  test_splits: [ "eval" ]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  generate_cfg:
    max_len: 250
    min_len: 1
    num_beams: 5
```
