### ISSUE TITLE
Error AssertionError: max_iters must be greater than 0.

### ISSUE THREAD

**Issue by shipengai** [opendatalab/VIGC#15]
when train with vigc/projects/mini_gpt4_vicuna7b/vigc/llava-150k/normal_vigc.yaml
```
run:
  runner: runner_iter
  task: instruct_blip_caption
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-5
  min_lr: 1e-5
  warmup_lr: 1e-6

  weight_decay: 0.05

  batch_size_train: 8
  batch_size_eval: 8
  num_workers: 4
  warmup_steps: 1000

  max_epoch: 5
  milestone: [ 1, 2, 3, 4, 5 ]
  accum_grad_iters: 2
```
when runner change from "runner_iter"  to "runner_base"， the code run success.

**Comment by shipengai** [comment]
@wufan-tb Can share the right train config？

**Comment by wufan-tb** [comment]
sure, I find one of our expriment config, you can take it as an reference: 
```
run:
  runner: runner_base
  task: instruct_blip_caption
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-5
  min_lr: 1e-5
  warmup_lr: 1e-6

  weight_decay: 0.05

  batch_size_train: 8
  batch_size_eval: 8
  num_workers: 4
  warmup_steps: 1000

  max_epoch: 5
  milestone: [1, 2, 3, 4, 5]
  accum_grad_iters: 2

  seed: 42
  output_dir: "output/ckpt/vigc7b_stage3/add_detail_rep2"

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: [ "train" ]
  valid_splits: [ "eval" ]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  generate_cfg:
    max_len: 256
    min_len: 8
    num_beams: 5
```
Yet our code was optimized before released on github, some of these keys may have changed.
