### ISSUE TITLE
Severe Hallucination in Generated Descriptions for Construction Site Dataset

### ISSUE THREAD

**Issue by GRD-Chang** [opendatalab/VIGC#19]
Hello,
I've encountered a issue while testing with a construction site dataset. The descriptions generated by the model are severely mismatched with the actual images. I would appreciate any insights or suggestions on how to address this issue.
image:
![image](https://github.com/user-attachments/assets/950f833d-ae6d-4c1e-b5f3-3798d128a8fe)
output:
`{"image": "imgs/36.png", "instruction": "Generate a question to describe the image content in detail and then answer it.", "image_id": 36, "whole_text": "Generate a question to describe the image content in detail and then answer it. Question: Can you describe the main features of this image for me? Answer: The image depicts a construction site with a large crane in the center of the scene. The crane appears to be in the process of lifting a piece of scaffolding, which is suspended from the crane's boom. The scaffolding is positioned high above the ground, and the crane's boom is extended to reach it. In addition to the crane and scaffolding, there are several other objects scattered throughout the scene.", "answer": "The image depicts a construction site with a large crane in the center of the scene. The crane appears to be in the process of lifting a piece of scaffolding, which is suspended from the crane's boom. The scaffolding is positioned high above the ground, and the crane's boom is extended to reach it. In addition to the crane and scaffolding, there are several other objects scattered throughout the scene.", "original_answer": "The image depicts a construction site with a large crane in the center of the scene. The crane appears to be in the process of lifting a piece of scaffolding, which is suspended from the crane's hook. The scaffolding is positioned towards the right side of the image, while the crane takes up a significant portion of the left side.\n\nIn addition to the crane and scaffolding, there are several people visible in the scene. They are scattered around the construction site, some closer to the crane and others further away. Overall, the image portrays a busy and active construction site with various equipment and personnel at work.", "answer_given_question": "The image depicts a construction site with a large crane in the center of the scene. The crane appears to be in the process of lifting something, possibly a piece of scaffolding or another construction material. The crane's boom is positioned towards the left side of the image, while the rest of the crane extends towards the right side.\n\nIn addition to the crane, there are several people visible in the scene. They are scattered around the construction site, some closer to the crane and others further away. Overall, the image captures a glimpse of a busy construction site with various workers and machinery at work.", "question": "Can you describe the main features of this image for me?", "answer_lst": []}`
config:
/home/github/VIGC/vigc/projects/mini_gpt4_vicuna13b/generate_qa/llava-150k/generate_llava_qa_detail.yaml
```
model:
  arch: blip2_vicuna_instruct
  model_type: minigpt4_vicuna13b
  finetuned: "/home/github/checkpoint/vigc13b_minigpt4_llava/vigc13b_minigpt4_llava.pth"

datasets:
  instruct_blip_coco2017_vig_test: # name of the dataset builder

    filter:
      - llava
    vis_processor:
      eval:
        name: "blip_image_eval"
        image_size: 224
    text_processor:
      eval:
        name: "blip_caption_instruct"
        max_words: 256

run:
  runner: runner_iter
  task: instruct_blip_llava_vig
  answer_length: 4
  llava_task: desc  # desc, comp or conv
  gen_style: vig  # vig or vic

  batch_size_train: 16
  batch_size_eval: 4
  num_workers: 4

  iters_per_inner_epoch: 2000
  max_iters: 60000

  seed: 42
  output_dir: "output/result/minigpt4_13b_llava/detail"

  evaluate: True
  test_splits: [ "eval" ]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  generate_cfg:
    max_len: 250
    min_len: 1
    num_beams: 5
```
/home/github/VIGC/vigc/configs/models/mini_gpt4_vicuna13b.yaml:
```
model:
  arch: instruct_vicuna13b
  load_finetuned: True
  load_pretrained: True

  pretrained: "/home/github/checkpoint/pretrained_minigpt4_stage1.pth"
  finetuned: "/home/github/checkpoint/vigc13b_minigpt4_llava/vigc13b_minigpt4_llava.pth"

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # path to Vicuna checkpoint
  llm_model: "/home/vicuna-13b-v1.1"

  # generation configs
  prompt: ""


preprocess:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
        eval:
          name: "blip_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
```
